### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.13

### ISSUE THREAD

**Issue by gares** [coq-community/coq-ext-lib#102]
The Coq team is planning to release Coq 8.13-beta1 on December 7, 2020
and Coq 8.13.0 on January 7, 2020.

Your project is currently scheduled for being bundled in the Windows installer.

We are currently testing commit 159c36111a95e5e587020c9f10b2e2ecd9fa3914
on branch https://github.com/coq-community/coq-ext-lib/tree/master
but we would like to ship a released version instead (a tag in git's slang).

Could you please tag that commit, or communicate us any other tag
that works with the Coq branch v8.13 at the *latest* 15 days before the
date of the final release?

Thanks!
CC: https://github.com/coq/coq/issues/12334

**Comment by liyishuai** [comment]
https://github.com/coq-community/coq-ext-lib/releases/tag/v0.11.3

**Comment by gares** [comment]
thanks!
