### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.14

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/coq-ext-lib#116]
The Coq team released Coq 8.14+rc1 on September 17, 2021
and plans to release Coq 8.14.0 before October 31, 2021.
A corresponding Coq Platform releases should be released before November 30, 2021.
It can be dealyed in case of difficulties until January 31, 2022, but this should be an exception.

Coq CI is currently testing commit 968fb49a1f1044adf87f8e427cbe2d83d525d37d
on branch https://github.com/coq-community/coq-ext-lib/tree/master
but we would like to ship a released version instead (a tag in git's slang).

Coq Platform is currently testing opam version dev
from official repository https://coq.inria.fr/opam/extra-dev.

Could you please create a tag, or communicate us any existing tag that works with
Coq branch v8.14, preferably 15 days before November 30, 2021
or earlier? In case we might have to delay the Coq Platform release cause of issues with
your project, we would prefer to be informed about the situation as early as possible.

Thanks!

P.S.: this issue has been creates semi-automatically.

CC: https://github.com/coq/platform/issues/139

**Comment by liyishuai** [comment]
[v0.11.4](https://github.com/coq-community/coq-ext-lib/releases/tag/v0.11.4) has been tested against Coq 8.14-rc1.

**Comment by MSoegtropIMC** [comment]
Thanks - this works on Coq Platform CI! I will do a PR for the opam package (will put you on CC).
