### ISSUE TITLE
Right Idenity in MonadLaw

### ISSUE THREAD

**Issue by mukeshtiwari** [coq-community/coq-ext-lib#117]
In the MonadLaw, there is no right identity but  based on my understanding, so far, we need to have left identity, right identity, and associativity. Is it a deliberate decision (or I am missing something)?  

https://github.com/coq-community/coq-ext-lib/blob/aeb71ca2f5e5538f23f287772d3d84b35241415a/theories/Structures/MonadLaws.v#L22

[1] [Haskell Monad Law Page](https://wiki.haskell.org/Monad_laws)

**Comment by Lysxia** [comment]
You're right, there should be that extra law.

**Comment by liyishuai** [comment]
Not sure why I removed it in 80d98c8d94dba49e934a1e2f4533f75097f22ed1. Worth adding back.
