### ISSUE TITLE
Metadata problem with release 0.12.1 on opam

### ISSUE THREAD

**Issue by shinnar** [coq-community/coq-ext-lib#143]
Our project (which uses coq-ext-libs as a dependency) has started failing in CI as of the newest release.  We were not constraining the version of coq-ext-lib.

Apparently, opam is now reporting 'coq-ext-lib.1.2.1' as the latest available, and then responding with a 404 error when it tries to fetch it.

I suspect that there may have been some metadata error (a misplaced period in a version string) when creating the 0.12.1 release.

A workaround for the moment is to add an upper version bound to our opam file (https://github.com/IBM/FormalML/commit/8f40fe44491f3beec143cacbe31dcde449f513ff).  Note that this causes opam to pull in version 0.12.0.

**Comment by liyishuai** [comment]
1.2.1 is a wrong version number, and is removed in coq/opam#2972
`opam update` might do the same job.

Side note: if you prefer to have ExtLib track the latest development of `Formal_ML`, you may consider releasing it in coq-released or coq-extra-dev.

**Comment by liyishuai** [comment]
@shinnar Are you still impacted by the metadata issue?

Propose closing as resolved, if no issues arise by Fri 22 Mar.
