### ISSUE TITLE
Operator priority

### ISSUE THREAD

**Issue by liyishuai** [coq-community/coq-ext-lib#78]
`<$>` is looser than `>>=`, causing `f <$> g >>= h` to be `f <$> (g >>= h)` rather than `(f <$> g) >>= h`, which is different from Haskell.
I'd propose:
- [ ] Align priority order with Haskell (wherever possible) to avoid such confusion.
- [ ] Document all notations somewhere.

**Comment by gmalecha** [comment]
Interesting. I thought this was already fixed, but maybe I was mistaken. Definitely should do it.
