### ISSUE TITLE
Why `Applicative_Fun` instance is local?

### ISSUE THREAD

**Issue by vzaliva** [coq-community/coq-ext-lib#88]
We have `Local Instance Applicative_Fun` in `ExtLib/Data/Fun.v`. This makes it undiscoverable during typeclass search and I have to write:

`liftA2 (AT:=(Applicative_Fun _)) f x y`

instead of just:

`liftA2 f x y`

**Comment by gmalecha** [comment]
Let's try to make it global. I think I was potentially worried about it unifying too many places and therefore being difficult to use.

**Comment by vzaliva** [comment]
I am tyring to make PR. FYI master branch does not compile:

```
$ make                                                    
Makefile:3: coqdocjs/Makefile.doc: No such file or directory
make: *** No rule to make target 'coqdocjs/Makefile.doc'.  Stop.
```

the file is indeed missing.

**Comment by vzaliva** [comment]
what about `Functor_Fun` and the rest of the instances in Fun.v?
