### ISSUE TITLE
Add the let* monadic notation

### ISSUE THREAD

**Issue by lthms** [coq-community/coq-ext-lib#95]
Hi,

Thanks for ext-lib, it looks like a very carefully written library. I am considering dropping my home-made `Monad` typeclass for `ExtLib`, but I was wondering if you would be willing to add the `let* x := p in q` notation that matches whatOCaml has recently added.

It is possible to keep both, I think (`_ <- _;; _` and `let* _ := _ in _`).

What do you think? I can propose a patch if you agree.

Thanks by advance!

**Comment by liyishuai** [comment]
Adding a notation module in parallel with the existing `MonadNotation` should be fine and won't break things. Please feel free to proceed.

**Comment by vzaliva** [comment]
now we just need proof-general support for `let*` indentation ;)

**Comment by lthms** [comment]
In fact, I think it already does!
